<?php $s = "  Hello World  "; ?>
<?= strlen($s) ?>
<?= strtolower($s) ?>
<?= strtoupper($s) ?>
<?= trim($s) ?>
<?= str_replace("World", "PHP", $s) ?>
<?php $t = "abcdef"; ?>
<?= substr($t, 2, 3) ?>
<?= strpos($t, "cd") ?>
<?= str_repeat("ab", 3) ?>
<?= ucfirst("hello world") ?>
<?= ucwords("hello world") ?>
<?= sprintf("%.2f", 3.14159) ?>
<?= number_format(1234567.891, 2) ?>
