<?php require "model.py"; ?>
<?php
if (!isset($argv[1])) {
    echo "Usage: python3 -m pyphp examples/c_header/header.php <model.xml>\n";
    exit(1);
}
$model = new Model($argv[1]);
?>
<?php $structs = $model->structs(); ?>
// Generated by codegen utility
#pragma once
#include <stdint.h>

<?php foreach ($structs as $struct): ?>
typedef struct <?= $struct->name ?> <?= $struct->name ?>, *lp<?= $struct->name ?>;
struct <?= $struct->name ?> {
<?php $fields = $struct->findall("field"); ?>
<?php foreach ($fields as $field): ?>
    <?= $field->type ?> <?= $field->name ?>;
<?php endforeach ?>
};

<?php endforeach ?>
